version: '3'

services:
    postgres:
        image: postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: sampledb
            POSTGRES_USER: sampledb
            POSTGRES_PASSWORD: sampledb123
        volumes:
            - ./docker/postgres/sampledb.sql:/docker-entrypoint-initdb.d/1-schema.sql
            - ./docker/postgres:/var/lib/postgresql